name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:4748a72706ff934a17662446862ca4f89d7014eabb9bd1b26eef9787fcea5797
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
